### ISSUE TITLE
项目识别的图片结果一直为1.008Mpa

### ISSUE THREAD

**Issue by GPT0x01** [zhahoi/YoloX-DeepLabV3Plus-MeterReader#2]
<img width="862" alt="71bc631c55faed8fb69c48e200a2efc" src="https://github.com/user-attachments/assets/804363ac-d987-480a-8630-7b217cb1f002">

![image](https://github.com/user-attachments/assets/3d9c6d42-7898-48b3-9e9c-7b4589bc29c5)

![image](https://github.com/user-attachments/assets/edad703c-9d9e-49c9-bf8d-8cb20acfcf10)

您好，我这边用您的代码运行了一下，结果一直识别为1,就是项目中的权重是训练过的吗，还是需要重新训练

**Comment by GPT0x01** [comment]
错了

**Comment by zhahoi** [comment]
你好，我当前的代码是针对于某种特定仪表来进行处理的，如果是其他种类的仪表，应该在代码的某些部分做相应的调整，我抽时间整理一份说明。

**Comment by zhahoi** [comment]
或者你留一个联系方式，可以看看哪里出现的问题。
